### ISSUE TITLE
Building on windows: issue and solution.

### ISSUE THREAD

**Issue by LovelyXandy** [lancaster-university/microbit-v2-samples#14]
Took me a while to work out - the build.py (and associated scripts) on a windows machine fail with a not very useful error if the directory path contains a space character (which github desktop defaults to including); they also won't download the libraries from the other githubs unless the path to the git command line executable is added (which the desktop github for windows doesn't do automatically).

**Comment by finneyj** [comment]
Thanks for reporting @LovelyXandy. Sorry to hear you didn't have the smoothest ride here.

Perhaps you could advise a fix when you have a bit of spare time @jamesadevine? I think you know that script better than anyone?

**Comment by jamesadevine** [comment]
Have you got a repro @LovelyXandy?

**Comment by martinwork** [comment]
I think https://github.com/lancaster-university/microbit-v2-samples/pull/10 will help build.py work with spaces.

I haven't hit the problem with the git command path.

**Comment by microbit-carlos** [comment]
PR created:
- https://github.com/lancaster-university/codal/pull/50
