### ISSUE TITLE
Should we add code on top of yours, or post compatible with the previous pxt?

### ISSUE THREAD

**Issue by hnwangkg-ezio** [lancaster-university/microbit-v2-samples#20]
Should we add code on top of yours, or post compatible with the previous pxt?

**Comment by hnwangkg-ezio** [comment]
Because what we developed before is like this:
https://github.com/waveshare/WSLCD1in8
It is microbit V1, now microbit V2 is not supported, I need to know how to modify it to support V2

**Comment by hnwangkg-ezio** [comment]
Because this problem has been dealt with for more than a week, I don’t have a good idea, can anyone help me?

**Comment by microbit-carlos** [comment]
Hi @hnwangkg-ezio, have you been able to update the extension for V2 compatibility or do you still need some assitance?

**Comment by microbit-carlos** [comment]
I'll close this issue due to lack of activity, but please do reopen it if you still need any help 👍
