### ISSUE TITLE
GCC ARM not working on macOS Catalina despite being installed and added to PATH

### ISSUE THREAD

**Issue by tmiliant** [lancaster-university/microbit-v2-samples#28]
The following is the error I got from the terminal after running "python build.py":

codal-microbit-v2 is already installed
Set target: codal-microbit-v2 
Using target.json (dev version) 
Targeting codal-microbit-v2
Supressing -Wexpansion-to-defined.
-- Adding library path: (/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries)
Installing dependencies...
codal-core is already installed
codal-nrf52 is already installed
codal-microbit-nrf5sdk is already installed
Using library: codal-microbit-v2
Using library: codal-core
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Using library: codal-nrf52
Using library: codal-microbit-nrf5sdk
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/valentine_qkd/Desktop/microbit-v2-samples-master/build
[  1%] Building CXX object libraries/codal-core/CMakeFiles/codal-core.dir/source/core/CodalComponent.cpp.o
[  1%] Building CXX object libraries/codal-core/CMakeFiles/codal-core.dir/source/core/CodalFiber.cpp.o
[  1%] Building CXX object libraries/codal-core/CMakeFiles/codal-core.dir/source/core/codal_default_target_hal.cpp.o
[  1%] Building CXX object libraries/codal-core/CMakeFiles/codal-core.dir/source/core/CodalHeapAllocator.cpp.o
[  1%] Building CXX object libraries/codal-core/CMakeFiles/codal-core.dir/source/driver-models/Timer.cpp.o
[  2%] Building CXX object libraries/codal-core/CMakeFiles/codal-core.dir/source/driver-models/AbstractButton.cpp.o
[  2%] Building CXX object libraries/codal-core/CMakeFiles/codal-core.dir/source/driver-models/Sensor.cpp.o
[  2%] Building CXX object libraries/codal-core/CMakeFiles/codal-core.dir/source/drivers/HIDMouse.cpp.o
[  2%] Building CXX object libraries/codal-core/CMakeFiles/codal-core.dir/source/drivers/Button.cpp.o
[  3%] Building CXX object libraries/codal-core/CMakeFiles/codal-core.dir/source/drivers/ILI9341.cpp.o
clang: clangwarning: : warning-Wl,--gc-sections: 'linker' input unused [-Wunused-command-line-argument]: 
-Wl,--gc-sections: 'linker' input unused [-Wunused-command-line-argument]clang: 
warningclang: : -Wl,--sort-common: 'linker' input unused [-Wunused-command-line-argument]warning: 
-Wl,--sort-common: 'linker' input unused [-Wunused-command-line-argument]clang: 
warningclang: : -Wl,--sort-section=alignment: 'linker' input unused [-Wunused-command-line-argument]warning: 
-Wl,--sort-section=alignment: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mcpu=cortex-m4' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfpu=fpv4-sp-d16' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mcpu=cortex-m4' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfpu=fpv4-sp-d16' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
clang: warning: -Wl,--gc-sections: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-common: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-section=alignment: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mcpu=cortex-m4' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfpu=fpv4-sp-d16' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
clang: warning: -Wl,--gc-sections: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-common: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-section=alignment: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mcpu=cortex-m4' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfpu=fpv4-sp-d16' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
clang: warning: -Wl,--gc-sections: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-common: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-section=alignment: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mcpu=cortex-m4' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfpu=fpv4-sp-d16' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
clang: warning: -Wl,--gc-sections: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-common: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-section=alignment: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mcpu=cortex-m4' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfpu=fpv4-sp-d16' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
clang: warning: -Wl,--gc-sections: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-common: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-section=alignment: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mcpu=cortex-m4' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfpu=fpv4-sp-d16' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
clang: warning: -Wl,--gc-sections: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-common: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-section=alignment: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mcpu=cortex-m4' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfpu=fpv4-sp-d16' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
clang: warning: -Wl,--gc-sections: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-common: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-section=alignment: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mcpu=cortex-m4' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfpu=fpv4-sp-d16' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
clang: warning: -Wl,--gc-sections: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-common: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-section=alignment: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mcpu=cortex-m4' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfpu=fpv4-sp-d16' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalComponent.cpp:28:
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/driver-models/Timer.h:293:30: warning: 
      unknown attribute 'long_call' ignored [-Wunknown-attributes]
    __attribute__((noinline, long_call, section(".data")))
                             ^
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/driver-models/Timer.h:293:49: error: 
      argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment and
      section separated by a comma
    __attribute__((noinline, long_call, section(".data")))
                                                ^
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalComponent.cpp:26:
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/CodalFiber.h:41:
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/EventModel.h:56:18: warning: 
      private field 'eventHandle' is not used [-Wunused-private-field]
        uint16_t eventHandle;
                 ^
2 warnings and 1 error generated.
make[2]: *** [libraries/codal-core/CMakeFiles/codal-core.dir/source/core/CodalComponent.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/driver-models/Sensor.cpp:35:
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/driver-models/Timer.h:293:30: warning: 
      unknown attribute 'long_call' ignored [-Wunknown-attributes]
    __attribute__((noinline, long_call, section(".data")))
In file included from                              ^/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/drivers/Button.cpp
:27:
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/driver-models/Timer.h:/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/driver-models/Timer.h:293:49: error: 
      argument to293 :'section'30 :attribute  is warningnot:  valid for 
this       unknowntarget:  attributemach-o  'long_call'section  ignoredspecifier  [-Wunknown-attributes]requires 
a segment and
      section separated by a comma
    __attribute__((noinline, long_call, section(".data")))
                                                ^
    __attribute__((noinline, long_call, section(".data")))
                             ^
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/driver-models/Timer.h:293:49: error: 
      argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment and
      section separated by a comma
    __attribute__((noinline, long_call, section(".data")))
                                                ^
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/driver-models/Timer.cpp:37:
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/driver-models/Timer.h:293:30: warning: 
      unknown attribute 'long_call' ignored [-Wunknown-attributes]
    __attribute__((noinline, long_call, section(".data")))
                             ^
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/driver-models/Timer.h:293:49: error: 
      argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment and
      section separated by a comma
    __attribute__((noinline, long_call, section(".data")))
                                                ^
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/driver-models/Sensor.cpp:34:
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/CodalFiber.h:41:
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/EventModel.h:56:18: warning: 
      private field 'eventHandle' is not used [-Wunused-private-field]
        uint16_t eventHandle;
                 ^
2 warnings and 1 error generated.
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/codal_default_target_hal.cpp:4:
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/driver-models/Timer.h:293:30: warning: 
      unknown attribute 'long_call' ignored [-Wunknown-attributes]
    __attribute__((noinline, long_call, section(".data")))
                             ^
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/driver-models/Timer.h:293:49: error: 
      argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment and
      section separated by a comma
    __attribute__((noinline, long_call, section(".data")))
                                                ^
make[2]: *** [libraries/codal-core/CMakeFiles/codal-core.dir/source/driver-models/Sensor.cpp.o] Error 1
1 warning and 1 error generated.
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/driver-models/AbstractButton.cpp:27:
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/driver-models/Timer.h:293:30: warning: 
      unknown attribute 'long_call' ignored [-Wunknown-attributes]
    __attribute__((noinline, long_call, section(".data")))
                             ^
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/driver-models/Timer.h:293:49: error: 
      argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment and
      section separated by a comma
    __attribute__((noinline, long_call, section(".data")))
                                                ^
make[2]: *** [libraries/codal-core/CMakeFiles/codal-core.dir/source/core/codal_default_target_hal.cpp.o] Error 1
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/drivers/Button.cpp:28:
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/EventModel.h:56:18: warning: 
      private field 'eventHandle' is not used [-Wunused-private-field]
        uint16_t eventHandle;
                 ^
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalHeapAllocator.cpp:160:21: warning: 
      cast to 'unsigned int *' from smaller integer type 'uint32_t' (aka 'unsigned int') [-Wint-to-pointer-cast]
    h->heap_start = (PROCESSOR_WORD_TYPE *)start;
                    ^
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalHeapAllocator.cpp:161:19: warning: 
      cast to 'unsigned int *' from smaller integer type 'uint32_t' (aka 'unsigned int') [-Wint-to-pointer-cast]
    h->heap_end = (PROCESSOR_WORD_TYPE *)end;
                  ^
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalHeapAllocator.cpp:164:49: error: 
      cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
    *h->heap_start = DEVICE_HEAP_BLOCK_FREE | (((PROCESSOR_WORD_TYPE) h->heap_end - (PROCESSOR_WORD_TYPE) h...
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalHeapAllocator.cpp:164:85: error: 
      cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
  ...= DEVICE_HEAP_BLOCK_FREE | (((PROCESSOR_WORD_TYPE) h->heap_end - (PROCESSOR_WORD_TYPE) h->heap_start) / DEV...
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalHeapAllocator.cpp:411:47: error: 
      aliases are not supported on darwin
void *malloc(size_t sz) __attribute__ ((weak, alias ("device_malloc")));
                                              ^
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalHeapAllocator.cpp:412:44: error: 
      aliases are not supported on darwin
void free(void *mem) __attribute__ ((weak, alias ("device_free")));
                                           ^
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalHeapAllocator.cpp:413:62: error: 
      aliases are not supported on darwin
void* realloc (void* ptr, size_t size) __attribute__ ((weak, alias ("device_realloc")));
                                                             ^
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalHeapAllocator.cpp:53:
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/CodalDevice.h:31:
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/CodalFiber.h:41:
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/EventModel.h:56:18: warning: 
      private field 'eventHandle' is not used [-Wunused-private-field]
        uint16_t eventHandle;
                 ^
2 warnings and 1 error generated.
3 warnings and 5 errors generated.
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalFiber.cpp:35:
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/driver-models/Timer.h:293:30: warning: 
      unknown attribute 'long_call' ignored [-Wunknown-attributes]
    __attribute__((noinline, long_call, section(".data")))
                             ^
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/driver-models/Timer.h:293:49: error: 
      argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment and
      section separated by a comma
    __attribute__((noinline, long_call, section(".data")))
                                                ^
make[2]: *** [libraries/codal-core/CMakeFiles/codal-core.dir/source/drivers/Button.cpp.o] Error 1
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalFiber.cpp:235:38: error: 
      cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
    tcb_configure_lr(idleFiber->tcb, (PROCESSOR_WORD_TYPE)&idle_task);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [libraries/codal-core/CMakeFiles/codal-core.dir/source/core/CodalHeapAllocator.cpp.o] Error 1
1 warning and 1 error generated.
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalFiber.cpp:675:53: error: 
      cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
    tcb_configure_lr(newFiber->tcb, parameterised ? (PROCESSOR_WORD_TYPE) &launch_new_fiber_param : (PROCES...
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalFiber.cpp:675:101: error: 
      cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
  ...parameterised ? (PROCESSOR_WORD_TYPE) &launch_new_fiber_param : (PROCESSOR_WORD_TYPE) &launch_new_fiber);
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalFiber.cpp:698:27: error: 
      cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
    return __create_fiber((uint32_t) entry_fn, (uint32_t)completion_fn, 0, 0);
                          ^~~~~~~~~~~~~~~~~~~
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalFiber.cpp:698:48: error: 
      cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
    return __create_fiber((uint32_t) entry_fn, (uint32_t)completion_fn, 0, 0);
                                               ^~~~~~~~~~~~~~~~~~~~~~~
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalFiber.cpp:719:27: error: 
      cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
    return __create_fiber((uint32_t) entry_fn, (uint32_t)completion_fn, (uint32_t) param, 1);
                          ^~~~~~~~~~~~~~~~~~~
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalFiber.cpp:719:48: error: 
      cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
    return __create_fiber((uint32_t) entry_fn, (uint32_t)completion_fn, (uint32_t) param, 1);
                                               ^~~~~~~~~~~~~~~~~~~~~~~
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalFiber.cpp:719:73: error: 
      cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
    return __create_fiber((uint32_t) entry_fn, (uint32_t)completion_fn, (uint32_t) param, 1);
                                                                        ^~~~~~~~~~~~~~~~
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalFiber.cpp:757:18: warning: 
      cast to 'void *' from smaller integer type 'uint32_t' (aka 'unsigned int') [-Wint-to-void-pointer-cast]
            free((void *)p->stack_bottom);
                 ^
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalFiber.cpp:832:18: warning: 
      cast to 'void *' from smaller integer type 'uint32_t' (aka 'unsigned int') [-Wint-to-void-pointer-cast]
            free((void *)f->stack_bottom);
                 ^
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalFiber.cpp:835:27: error: 
      cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
        f->stack_bottom = (PROCESSOR_WORD_TYPE)malloc(bufferSize);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [libraries/codal-core/CMakeFiles/codal-core.dir/source/driver-models/Timer.cpp.o] Error 1
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalFiber.cpp:942:46: error: 
      cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
            tcb_configure_lr(idleFiber->tcb, (PROCESSOR_WORD_TYPE)&idle_task);
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/driver-models/AbstractButton.cpp:28:
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/EventModel.h:56:18: warning: 
      private field 'eventHandle' is not used [-Wunused-private-field]In file included from 
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/core/CodalFiber.cpp:34:
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/CodalFiber.h:        uint16_t eventHandle;41
:
                 ^/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/EventModel.h
:56:18: warning: 
      private field 'eventHandle' is not used [-Wunused-private-field]
        uint16_t eventHandle;
                 ^
2 warnings and 1 error generated.
4 warnings and 11 errors generated.
[  3%] Building CXX object libraries/codal-core/CMakeFiles/codal-core.dir/source/drivers/KeyValueStorage.cpp.o
make[2]: *** [libraries/codal-core/CMakeFiles/codal-core.dir/source/core/CodalFiber.cpp.o] Error 1
make[2]: *** [libraries/codal-core/CMakeFiles/codal-core.dir/source/driver-models/AbstractButton.cpp.o] Error 1
clang: warning: -Wl,--gc-sections: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-common: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--sort-section=alignment: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mcpu=cortex-m4' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfpu=fpv4-sp-d16' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/drivers/ILI9341.cpp:2:
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/CodalFiber.h:41:
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/EventModel.h:56:18: warning: 
      private field 'eventHandle' is not used [-Wunused-private-field]
        uint16_t eventHandle;
                 ^
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/source/drivers/KeyValueStorage.cpp:32:
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/drivers/KeyValueStorage.h:30:
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/types/ManagedString.h:29:
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/types/RefCounted.h:29:
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/CodalDevice.h:31:
In file included from /Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/CodalFiber.h:41:
/Users/valentine_qkd/Desktop/microbit-v2-samples-master/libraries/codal-core/./inc/core/EventModel.h:56:18: warning: 
      private field 'eventHandle' is not used [-Wunused-private-field]
        uint16_t eventHandle;
                 ^
1 warning generated.
1 warning generated.
make[1]: *** [libraries/codal-core/CMakeFiles/codal-core.dir/all] Error 2
make: *** [all] Error 2

I installed the tar file from the photo below(should I have installed the package as well?):

<img width="604" alt="Screenshot 2021-03-11 at 13 51 32" src="https://user-images.githubusercontent.com/58377307/110783357-01520580-8271-11eb-90a3-792c993138c4.png">

Then I expanded the tar file and moved the result to /usr/local with "sudo mv (download path) /usr/local/gcc-arm".

The following are my paths in /etc/paths, after adding the binaries to the path:
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/usr/local/gcc-arm/bin

The following is the path of interest in ~/.bash_profile:
export PATH=$PATH:/usr/local/gcc-arm/bin

I did all of the above on two different macOS, both with Catalina on them. Same errors in the same order.

Below is photo showing I have everything that is required installed:
<img width="938" alt="Screenshot 2021-03-11 at 13 56 04" src="https://user-images.githubusercontent.com/58377307/110783811-9654fe80-8271-11eb-8993-86bb49c46b8d.png">

**Comment by jamesadevine** [comment]
I'd check to see if the terminal window you are compiling from is using the updated path.

Would be great to see your cmake version if possible...

**Comment by tmiliant** [comment]
I had also installed arm-none-eabi-gcc using "brew install ..." that is why at the end of the issue it shows up with 2019 instead of 2020. When I try to invoke arm-none-eabi-gcc as suggested by the readme.txt, it gives me this:
<img width="352" alt="Screenshot 2021-03-11 at 14 16 41" src="https://user-images.githubusercontent.com/58377307/110786119-6a874800-8274-11eb-8678-fb61f7431d70.png">

**Comment by tmiliant** [comment]
I also tried running "python build.py" without having installed anything related to gcc arm. The exact same errors appear. This means that the process above is not doing anything, although I seem to have followed everything step by step.

**Comment by tmiliant** [comment]
![Uploading Screenshot 2021-03-11 at 14.25.12.png…]()

**Comment by tmiliant** [comment]
<img width="534" alt="Screenshot 2021-03-11 at 14 30 49" src="https://user-images.githubusercontent.com/58377307/110787735-63613980-8276-11eb-8bd7-ae1b8b6ff069.png">
<img width="639" alt="Screenshot 2021-03-11 at 14 30 13" src="https://user-images.githubusercontent.com/58377307/110787758-6c520b00-8276-11eb-9a43-90b41b7a713f.png">

**Comment by tmiliant** [comment]
<img width="480" alt="Screenshot 2021-03-11 at 15 37 34" src="https://user-images.githubusercontent.com/58377307/110795662-c5726c80-827f-11eb-9f9c-2d487b3e585d.png">

I installed cmake using "brew install cmake"

**Comment by tmiliant** [comment]
Where should the build.py file be located?

**Comment by tmiliant** [comment]
What is the logic behind it? How do I know which compiler the command "python build.py" is using?

When running "python build.py", it's fine because "which python" gives "/usr/bin/python" and "/usr/bin" is in the PATH. 

However the command "python build.py" does not contain "arm-none-eabi-gcc" which would make sense as "which arm-none-eabi-gcc" gives "/usr/local/gcc-arm/bin/arm-none-eabi-gcc" and I added "/usr/local/gcc-arm/bin/" to the path. 

By this logic should it not be "arm-none-eabi-gcc build.py"? Which part of "python build.py" is invoking the binaries of gcc-arm?
