### ISSUE TITLE
Can this compile for V1 micro:bit? 

### ISSUE THREAD

**Issue by joachimhs** [lancaster-university/microbit-v2-samples#32]
Can this docker image be used to compile the code for a V1 micro:bit, or is it only usable for V2s?

**Comment by carlosperate** [comment]
It's tailed specifically for V2, but it could be modified to install yotta and build V1 as well.
Alternatively you can try this one, the examples show how to use it with V1: https://github.com/carlosperate/docker-microbit-toolchain
