### ISSUE TITLE
Create `microbit-v2-samples` tag for next `codal-microbit-v2` release

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/microbit-v2-samples#67]
https://github.com/lancaster-university/microbit-v2-samples/compare/v0.2.12...master

There is a few changes in the main branch that would be good to ensure are correctly adopted by the upstream projects for the microbit 2023 release, so it'd be good to create a tag here as well for the next `codal-microbit-v2` release.

**Comment by microbit-carlos** [comment]
This might be currently blocked on this: https://github.com/lancaster-university/microbit-v2-samples/issues/70

**Comment by JohnVidler** [comment]
From #70, replicated here for tracking:

---

Patched out the F-strings as of f4aaca3a9ff55dfd79c9ec41024dbbc0bec4de04 on master.

Added in a couple of new args for `--status` while I was at it, including `-v` compliance for increased verbosity, and `-n` to control the number of log lines. Specifying a lib name on a `--status` call now also only shows that library on its own.

Example run: `./build.py -svn 12 codal-core` - aka, run versbose, with 12 log liens for _only_ the `codal-core` lib.

All flag combinations are handled correctly.

Note: The current default parallelism is `10` which should be fine for most systems, but is possibly suboptimal for 'big' build systems (like Makecode's backend, perhaps?) which may want to bump this up via `-j [number]` or `--parallelism [number]` for better build performance.

**Comment by microbit-carlos** [comment]
Reopening as we don't have a tag in https://github.com/lancaster-university/microbit-v2-samples/tags yet:

<img width="1131" alt="image" src="https://github.com/lancaster-university/microbit-v2-samples/assets/29712657/aeb4b6b4-9863-4878-a333-1501937d743e">

**Comment by JohnVidler** [comment]
Whup, sorry my mistake in closing the issue I misread this one - yes, needs a new tag but holding off for the second while we add some audio tests into the samples repo

**Comment by microbit-carlos** [comment]
Tag https://github.com/lancaster-university/microbit-v2-samples/releases/tag/v0.2.13 is out 👍
